apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  labels:
    app: hostpath-pod
spec:
  containers:
    - name: busybox-hostpath-pod
      image: busybox
      command: ["sleep", "3000"]
      volumeMounts:
        - name: hostpath-pvc
          mountPath: /var/tmp/mount-hostpath-pv
  volumes:
    - name: hostpath-pvc
      persistentVolumeClaim:
        claimName: hostpath-pvc
