apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc
  labels:
    storage: hostpath-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      storage: hostpath-pv
