apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
  labels:
    app: nfs-pod
spec:
  containers:
    - resources:
        limits:
          cpu: 0.25
      name: nfs-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nfs-vol
          mountPath: /tmp/nfs

  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: nfs-pvc
