apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep
  labels:
    name: mysql-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql-dep-pods
  template:
    metadata:
      labels:
        app: mysql-dep-pods
    spec:
      containers:
        - name: mysql-pods
          image: mysql:5.6
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-vars-cm
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
