apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
  labels:
    storage: hostpath-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle

  hostPath:
    path: /var/tmp/host-path-pv
