apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    storage: nfs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/nfs-pv
    server: 10.0.0.144
