apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv5g
  labels:
    storage: nfs-pv5g
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.0.0.144
    path: /mnt/nfs-pv5g
