apiVersion: batch/v1
kind: Job
metadata:
  name: perljob
  labels:
    job: perljob
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 3600
  template:
    spec:
      containers:
        - name: perl
          image: perl
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
