apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: dashboard-ingress
  namespace: kube-system
spec:
  rules:
    - host: kube-dashboard.elan.elantecs.com
      http:
        paths:
          - backend:
              serviceName: kubernetes-dashboard
              servicePort: 443
            path: /
# This section is only required if TLS is to be enabled for the Ingress
  tls:
      - hosts:
          - kube-dashboard.elan.elantecs.com
        secretName: tls-certificate
# If TLS is enabled for the Ingress, a Secret containing the certificate and key must also be provided:
