apiVersion: v1
kind: Pod
metadata:
  name: nginx-tol-pod
  labels:
    app: nginx-tol-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      ports:
        - containerPort: 80
  tolerations:
    - key: "fastnic"
      operator: "Equal"
      value: "true"
      effect: "NoExecute"
    - key: "fastnic"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "ssd"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io"
      operator: "Equal"
      value: "master"
      effect: "NoSchedule"
