apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis
spec:
  containers:
    - name: redis-cont
      image: redis
      volumeMounts:
        - name: empty-vol
          mountPath: /tmp/test

  restartPolicy: Always
  volumes:
    - name: empty-vol
      emptyDir: {}
