apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-task-rs
  labels:
    app: httpd-task-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-task-pods
  template:
    metadata:
      labels:
        app: httpd-task-pods
    spec:
      containers:
        - name: httpd-task-containers
          image: httpd
          ports:
            - containerPort: 80
