apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "30000"
      env:
        - name: MYSQL_ROOT_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-cmap
              key: MYSQL_ROOT_USER
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-cmap
              key: MYSQL_ROOT_PASSWORD         
