apiVersion: v1
kind: Pod
metadata:
  name: mysql-secret
  labels:
    app: mysql-secret
spec:
  containers:
    - name: mysql-secret
      image: mysql
      resources:
        limits:
          cpu: 0.25
      envFrom:
        - configMapRef:
            name: mysql-env-vars
      volumeMounts:
        - name: secrets
          mountPath: "/etc/secrets"
          readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: db-user-pass
  restartPolicy: Never
